baseURL = "https://taeko.cf"
languageCode = "en-us"
title = "Taeko's Blog!"
theme = "hugo-casper3-master"
copyright = "Copyright © 2020"
[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 10
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		url = "/post/"
		weight = 20
    	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 30
