baseURL = "https://taeko.cf"
languageCode = "en-us"
title = "Taeko's Blog!"
theme = "hugo-casper3-master"
copyright = "Copyright © 2020"
[menu]
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 10
